services:
  uniclogs-sdr:
    image: "uniclogs-sdr"
    hostname: uniclogs
    container_name: uniclogs
    command: "gnuradio-companion -c flowgraphs/lime_g3ruh.grc; python3 lime_g3ruh.py"
    ports:
      - "127.0.0.1:10006:10006/udp"
      - "127.0.0.1:10015:10015/udp"
      - "127.0.0.1:10025:10025/udp"
